### ISSUE TITLE
Bug in debug panel

### ISSUE THREAD

**Issue by whirm** [LipuFei/tribler#16]
```
Traceback (most recent call last):
  File "/var/data/feina/code/delft/tribler/Tribler/Main/vwxGUI/SearchGridManager.py", line 909, in _do_gui_callback
    callback(dslist, magnetlist)
  File "/var/data/feina/code/delft/tribler/Tribler/Main/vwxGUI/__init__.py", line 115, in invoke_func
    return func(*args, **kwargs)
  File "/var/data/feina/code/delft/tribler/Tribler/Main/vwxGUI/list.py", line 1819, in RefreshItems
    if torrent_ds and torrent_ds.get_seeding_statistics():
AttributeError: 'list' object has no attribute 'get_seeding_statistics'
Traceback (most recent call last):
  File "/var/data/feina/code/delft/tribler/Tribler/Main/vwxGUI/SearchGridManager.py", line 909, in _do_gui_callback
    callback(dslist, magnetlist)
  File "/var/data/feina/code/delft/tribler/Tribler/Main/vwxGUI/__init__.py", line 115, in invoke_func
    return func(*args, **kwargs)
  File "/var/data/feina/code/delft/tribler/Tribler/Main/vwxGUI/list.py", line 1819, in RefreshItems
    if torrent_ds and torrent_ds.get_seeding_statistics():
AttributeError: 'list' object has no attribute 'get_seeding_statistics'
Traceback (most recent call last):
  File "/var/data/feina/code/delft/tribler/Tribler/Main/vwxGUI/SearchGridManager.py", line 909, in _do_gui_callback
    callback(dslist, magnetlist)
  File "/var/data/feina/code/delft/tribler/Tribler/Main/vwxGUI/__init__.py", line 115, in invoke_func
    return func(*args, **kwargs)
  File "/var/data/feina/code/delft/tribler/Tribler/Main/vwxGUI/list.py", line 1819, in RefreshItems
    if torrent_ds and torrent_ds.get_seeding_statistics():
AttributeError: 'list' object has no attribute 'get_seeding_statistics'
Traceback (most recent call last):
  File "/var/data/feina/code/delft/tribler/Tribler/Main/vwxGUI/SearchGridManager.py", line 909, in _do_gui_callback
    callback(dslist, magnetlist)
  File "/var/data/feina/code/delft/tribler/Tribler/Main/vwxGUI/__init__.py", line 115, in invoke_func
    return func(*args, **kwargs)
  File "/var/data/feina/code/delft/tribler/Tribler/Main/vwxGUI/list.py", line 1819, in RefreshItems
    if torrent_ds and torrent_ds.get_seeding_statistics():
AttributeError: 'list' object has no attribute 'get_seeding_statistics'
ERROR   1416938363.43       community:554   TunnelCommunity: removing circuit 2477868525 no candidates to extend, bailing ou
```

**Comment by LipuFei** [comment]
@whirm This should be fixed, I added this line on line 1816.

```
torrent_ds = item.original_data.dslist[0]
```
